In [1]:
import numpy as np
my_list = [1,2,3,4]
type(my_list)

list

In [2]:
x = np.array(my_list)
type(x)

numpy.ndarray

In [3]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
type(matrix)

list

In [10]:
y = np.array(matrix)
print(y)
type(y)
y.shape


[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

In [12]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [13]:
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [14]:
np.zeros(4)

array([0., 0., 0., 0.])

In [16]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.random.rand(3)

array([0.68619285, 0.62290595, 0.84541465])

In [24]:
np.random.randn(3)

array([-0.01388077, -0.74321892,  2.14232029])

In [27]:
np.random.randn(5,5)

array([[-1.2278305 , -0.31222178, -0.27201909,  0.28282461,  0.16651665],
       [ 0.03228396,  1.54962896, -0.52424838, -0.87622142,  1.81556015],
       [-0.31554227,  1.19225072,  1.76521373, -0.04505124,  0.19004909],
       [-0.15730406, -0.36483272, -0.05343441,  0.12027127,  0.90465124],
       [-0.79295937, -0.29573043, -1.29299015,  0.29550197,  2.25550962]])

In [28]:
np.random.randint(0,100,10)

array([96, 43, 98, 29, 33, 97, 91, 44, 20, 93])

In [35]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [45]:
int_array = np.random.randint(1,20,10)
print(int_array)
print(int_array.max())
print(int_array.argmax())
print(int_array.min())
print(int_array.argmin())

[17  4  9 18  2 17  7 12 15  1]
18
3
1
9


In [58]:
list = [1,2,3,4,5,6,7,8,9,10]
array = np.array(list)
print(array[0:5])
print(array[array>6])
array[1:5] = 33
print(array[array>6])
print(array)
print(array>6)

[1 2 3 4 5]
[ 7  8  9 10]
[33 33 33 33  7  8  9 10]
[ 1 33 33 33 33  6  7  8  9 10]
[False  True  True  True  True False  True  True  True  True]


In [56]:
array_2d = np.array(([1,2,3],[4,5,6],[7,8,9]))
print(array_2d)
print(array_2d.shape)
print(array_2d[1:2,1:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
[[5 6]]


In [59]:
my_array = np.array([600,470,170,430,300])
mean = my_array.mean()
print(mean)
variance =  my_array.var()
print(variance)
standard =  my_array.std()
print(standard)

394.0
21704.0
147.32277488562318
