In [1]:
1 + 2

3

In [6]:
x = "Hello World"


In [7]:
len(x)


11

In [8]:
x[0]

'H'

In [9]:
x[:]

'Hello World'

In [165]:
b = "My name is Sameh"
b[::-1]

'hemaS si eman yM'

In [164]:
x = "Hello World"
y = x.replace("World", "test")
y

'Hello test'

In [5]:
x = [ 1,2,3]
x

[1, 2, 3]

In [6]:
x.clear()

In [17]:
x

[]

In [18]:
 o = [1 , 2 , 3]
o


[1, 2, 3]

In [19]:
o.pop(1)

2

In [20]:
o

[1, 3]

In [21]:
o.remove(1)

In [22]:
o

[3]

In [30]:
if (6 % 5 == 0) :
    print("even")
else :
    print("odd")
    

    

odd


In [8]:
x = input ("Enter First String")
x
    

Enter First String xdd


'xdd'

In [9]:
x

'xdd'

In [12]:
y = input ("Enter Second String")
y

Enter Second String jjj


'jjj'

In [13]:
x

'xdd'

In [14]:
z = x[::-1]
z

'ddx'

In [21]:
x = input ("Enter First String")
print(x)

y = input ("Enter Second String")
print(y)

z = x[::-1]
print(z)

if z == y :
    print("True")
else : 
    print("False")

Enter First String ASD


ASD


Enter Second String DSA


DSA
DSA
True


Enter First Number 13


13


Enter Second Number 12


12


Enter operation +


+


In [72]:
def calculate (first_num , second_num , operation) :
    
    result = 0
    
    if (operation == "add") :
        result = first_num + second_num
    elif (operation == "subtract") :
         result = first_num - second_num
    elif (operation == "multiply") :
         result = first_num * second_num
    elif (operation == "devide") :
         result = first_num / second_num
        
    print ("result = ", result)

In [73]:
calculate (10 , 30 , "add")

result =  40


In [74]:
calculate (20 , 10 , "subtract")

result =  10


In [75]:
calculate (30 , 10 , "multiply")

result =  300


In [78]:
calculate (200 , 100 , "devide")

result =  2.0


In [128]:
def total (*values) :
    sum = 0
    limit = len(values)
    for i in range(limit) :
        sum = sum + values[i]
    
    print(sum)     

In [129]:
total(1,5,2)

8


In [155]:
def greatest(*values) :
    sum = 0
    gretestValue = values[0]
    limit = len(values)
    for i in range(limit) :
        #if values[i] > gretestValue :
        if len(values[i]) > len(gretestValue) :
            gretestValue = values[i] 
    
    print(gretestValue) 

In [157]:
greatest("Tes123t", "Hello" , "1234567890")


1234567890


In [161]:
def averageValues(*values) :
    averageValue = 0
    sum = 0
    limit = len(values)
 
    for i in range(limit) :
        sum = sum + values[i]
    
    averageValue = sum / limit
    print(averageValue) 

In [162]:
averageValues(1,2,6)

3.0


In [166]:
import lib

In [167]:
lib.get_num(2)

3


In [200]:
f = open("Test.txt", "r")
print(f.read())
f.close()

Hi my name is Sameh


In [201]:
file = open("Test.txt", "r")
Lines = file.readlines()
for line in Lines:
    print(line)
    
Lines

Hi my name is Sameh


['Hi my name is Sameh']

In [182]:
file = open("Test.txt", "w")
file.write("Hi2")
file.close()

In [207]:
word = input("Enter first word")
#print(word)
character = input("Enter character")
print(character)
t = word.count(character)
print(t)       

Enter first word Hello 
Enter character J


J
0


In [218]:
file = open("Test.txt", "r")
Lines = file.readlines()
for line in Lines:
    #print(line)
    tokens = line.split()
    print(tokens)


['Hi', 'my', 'name', 'is', 'Sameh']
['Hi', 'my', 'name', 'is', 'Sameh', '2']
['Hi', 'my', 'name', 'is', 'Sameh', '3']


In [250]:
class car:
    num_cars = 0
    def __init__(self,name,age):
        num_cars += 1
    

In [251]:
class student:
    num_students = 0
    def __init_self(name,age,courses):
        num_students += 1
        self.name = name
        self.age = age
        self.cources = courses

In [273]:
class cat:
    num_cats = 0
    def __init__(self,name,age):
        cat.num_cats += 1
        self.name = name
        self.age = age 
    def show(self,color):
        self.color = color

In [277]:
cat1 = cat("name", 20)
cat2 = cat("name", 20)
cat3 = cat("name", 20)
cat4 = cat("name", 10)
cat.num_cats

10

In [275]:
cat.num_cats

3

In [286]:
class school :
    number_of_classes = 0
    def __init__(self,name,manager):
        self.name = name
        self.manager = manager
        school.number_of_classes += 10
        
    def greetManager(self):
        print("Hi ",self.manager)
    
    @classmethod
    def count_classes(cls):
        print("Number of schools classes ",cls.number_of_classes)
    
    @staticmethod
    def greetSchool():
        print("Hello School")

school1 = school("My School","My Manger")
school1.greetManager()

school2 = school("My School 2","My Manger 2")
school2.greetManager()

school.count_classes()

school.greetSchool()




Hi  My Manger
Hi  My Manger 2
Number of schools classes  20
Hello School


In [336]:
class person :
    def __init__(self,name):
        self.name = name
        
    def greet(self):
        print("Hello ",self.name)
        
p = person("name")
p.greet()
print("========================================")

class rectangle :
    def __init__(self,width,height):
        self.width = width
        self.height = height
        
    def area(self):
        self.area = self.width * self.height
        print("area ",self.area)

r = rectangle(10,20)
r.area()

print("========================================")

class bank_account :
    
    def __init__(self,balance):
        self.balance = balance
                
    def deposit(self,amount):
        self.balance = self.balance + amount
        print("balance ",self.balance)
        
    def withdraw(self,amount):
        self.balance = self.balance - amount
        print("balance ",self.balance)

ba = bank_account(300)
ba.deposit(20)
ba.withdraw(30)

print("========================================")

class car:
    
    def __init__(self,make,model,year):
        self.make = make
        self.model = model
        self.year = year
        
    def description(self):
        print("Make: ",self.make, "  - Model: ",self.model," - Year: ",self.year)

car = car("Kia" , "Proide" , "2020")
car.description()

print("========================================")

class Employee:
    
    def __init__(self,name,title,salary):
        self.name = name
        self.title = title
        self.salary = salary
        
    def  raise_salary(self, percentage):
        self.salary = self.salary + self.salary * percentage
        print("salary: ",self.salary)

emp = Employee("Mido" , "Mr" , 2000)
emp.raise_salary(0.1)

print("========================================")
import math
class Circle:
    
    def __init__(self,radius):
        self.radius = radius 

        
    def area(self):
        area = math.pi * self.radius * self.radius
        print("area: ",area)
    
    def circumference (self):
        circumference = 2 * math.pi * self.radius
        print("circumference : ", circumference)

circle = Circle(5)
circle.area()
circle.circumference()
print("========================================")

class Student:
    
    def __init__(self,name,grades):
        self.name = name
        self.grades = grades
        
    def average_grade(self):
        averageValue = 0
        sum = 0
        limit = len(self.grades)
 
        for i in range(limit) :
            sum = sum + self.grades[i]
    
        averageValue = sum / limit
        print("average_grade ", averageValue)

grades = [5 ,5 , 5 , 5 ,5]
student = Student("Ahmed" , grades)
student.average_grade()
print("========================================")

class Book:
    def __init__(self,title):
        self.title = title
        
class Library:
    def __init__(self,books):
        self.books = books
        
    def search(self, title):
        limit = len(self.books)
        for i in range(limit):
            if(self.books[i].title == title):
                print("Book Found")
    

books = [ Book("java") , Book("c#") , Book("python")]
library = Library(books)
library.search("java")




Hello  name
area  200
balance  320
balance  290
Make:  Kia   - Model:  Proide  - Year:  2020
salary:  2200.0
area:  78.53981633974483
circumference :  31.41592653589793
average_grade  5.0
Book Found


In [32]:
def add_vectors(v1 , v2) :
    sum = 0
    z = [1,1]
    limit = len(v1)
    for i in range(limit) :
        x = v1[i]
        y = v2[i]
        sum = x + y
        #print(sum)
        z[i] = sum
        #print(z)

    print(z)
        
x = [2,6]
y = [2,1]
add_vectors(x,y)

[4, 7]


In [37]:
def multiply_vector(slizer , vector ):
    result = []
    for i in vector:
        result.append(slizer*i)
    return result

print((multiply_vector(2,[1,2,3])))    

[2, 4, 6]


In [77]:
def shape(matrix):
    num_rows = len(matrix)
    num_columns = len(matrix[0])
    return num_rows , num_columns 

matrix = [[1,2,3],[4,5,6],[7,8,9]]
print(shape(matrix))

(3, 3)


In [76]:
def add_2_matrix(matrix1,matrix2):
    result = [[0,0,0],
         [0,0,0]]
    
    
    for i in range(len(matrix1)):
        for j in range(len(matrix1[0])):
               result[i][j] = matrix1[i][j] + matrix2[i][j]
    return result

matrix1 = [[1,2,3],
           [1,2,3]]

matrix2 = [[1,2,3],
           [1,2,3]]

print(add_2_matrix(matrix1,matrix2)) 


[[2, 4, 6], [2, 4, 6]]


In [83]:
def multiply_2_matrix(matrix1,matrix2):
    result = [[0,0,0],
         [0,0,0]]
    
    
    for i in range(len(matrix1)):
        for j in range(len(matrix1[0])):
               result[i][j] = matrix1[i][j] * matrix2[i][j]
    return result

matrix1 = [[1,2,3],
           [1,2,3]]

matrix2 = [[1,2,3],
           [1,2,3]]

print(multiply_2_matrix(matrix1,matrix2)) 

matrix3 = [[1,2,3],
           [1,2,3]]

matrix4 = [[3,2,1],
           [3,2,1]]
print("===============")
print(multiply_2_matrix(matrix3,matrix4)) 
print("===============")


[[1, 4, 9], [1, 4, 9]]
[[3, 4, 3], [3, 4, 3]]


In [93]:
def dot(v , w):
    return sum([v_i * w_i for v_i , w_i in zip(v,w)])

def matrix_dot_vector(matrix , vector):
    result = []
    for i in range(len(matrix)):
        result.append(dot(matrix[i],vector))
    return result

matrix = [ [1,2] , 
           [3,4] , 
          [5,6] ]

vector = [0.5 , 
          0.5]

matrix_dot_vector(matrix , vector)
    

[1.5, 3.5, 5.5]

In [95]:
def multiply(c , v):
    z = float([ c*v_i for v_i in v])
    return z

def matrix_multiply_value(matrix , value):
    result = []
    for i in range(len(matrix)):
         result.append(multiply(matrix[i],value))
    return result

matrix3 = [ [1,2] , 
           [3,4] , 
          [5,6] ]

value = 1

# matrix_multiply_value(matrix3 , value)


    

In [107]:
import numpy as np
arr = np.array((([1,2,3],[4,5,6],[7,8,9])))  
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [105]:
arr[1:2,1:3]

array([[5, 6]])

In [108]:
import numpy as np
arr2 = np.array([1,2,3])  
arr2

array([1, 2, 3])

In [115]:
x = arr2.mean()
x

2.0

In [120]:
import numpy as np
my_array = np.array([600,470,170,430,300])
mean = my_array.mean()
print(mean)
variance =  my_array.var()
print(variance)
standard =  my_array.std()
print(standard)

394.0
21704.0
147.32277488562318
